package oracle

import (
	"strings"
	"testing"
	"time"

	types "dbbridge/pkg"
)

// demoSchema 模拟 MySQL 源库读出的表结构（小写表名/列名 + 自增主键）
func demoSchema() types.TableSchema {
	ten := 10
	return types.TableSchema{
		Name: "customers",
		Columns: []types.ColumnMeta{
			{Name: "id", BaseType: "INT", DataType: "INT", Nullable: false, IsPrimaryKey: true, AutoIncrement: true},
			{Name: "name", BaseType: "VARCHAR", DataType: "VARCHAR(64)", Nullable: false, Length: &ten},
		},
		Indexes: []types.IndexMeta{
			{Name: "PRIMARY", Columns: []string{"id"}, IsUnique: true, IsPrimary: true},
		},
	}
}

// 防回归：标识符必须规范化为大写（Oracle 惯例），不得按源库大小写带引号输出。
// 此前输出 "customers" 导致表以小写存储，而 TableExists 等用 UPPER() 判断，
// 第二次迁移误判表不存在、跳过 DROP 直接 CREATE，报 ORA-00955。
func TestGenerateCreateTableDDLUppercaseIdentifiers(t *testing.T) {
	a := &Adapter{brand: "Oracle"}
	ddl, err := a.GenerateCreateTableDDL(demoSchema())
	if err != nil {
		t.Fatalf("生成 DDL 失败: %v", err)
	}

	for _, want := range []string{
		"CREATE TABLE CUSTOMERS (",
		"ID NUMBER(10)",
		"NAME VARCHAR2(",
		"PRIMARY KEY (ID)",
	} {
		if !strings.Contains(ddl, want) {
			t.Errorf("DDL 缺少片段 %q\nDDL:\n%s", want, ddl)
		}
	}
	if strings.Contains(ddl, `"customers"`) || strings.Contains(ddl, `"id"`) {
		t.Errorf("DDL 不应包含小写引号标识符\nDDL:\n%s", ddl)
	}
}

func TestGenerateDropTableDDLUppercase(t *testing.T) {
	a := &Adapter{brand: "Oracle"}
	ddl, _ := a.GenerateDropTableDDL("customers")
	if ddl != `DROP TABLE CUSTOMERS PURGE` {
		t.Errorf("DROP DDL = %q, 期望大写无引号", ddl)
	}
}

// 含特殊字符的标识符才允许带引号，且内部大写化保持一致；
// Oracle 保留字（如 LEVEL）裸写会 ORA-00904，必须保持引号
func TestOraIdentSpecialChars(t *testing.T) {
	if got := oraIdent("order items"); got != `"ORDER ITEMS"` {
		t.Errorf("oraIdent(含空格) = %q", got)
	}
	if got := oraIdent(`a"b`); got != `"A""B"` {
		t.Errorf("oraIdent(含双引号) = %q", got)
	}
	if got := oraIdent("CUSTOMERS"); got != "CUSTOMERS" {
		t.Errorf("oraIdent(常规) = %q", got)
	}
	for _, w := range []string{"level", "order", "comment", "size", "rows", "date"} {
		if got := oraIdent(w); got != `"`+strings.ToUpper(w)+`"` {
			t.Errorf("oraIdent(保留字 %s) = %q, 期望带引号", w, got)
		}
	}
}

// INSERT 的表名列名同样必须大写化（迁移写入路径）
func TestWriteDataUppercaseIdentifiers(t *testing.T) {
	if got := quoteIdentifiers([]string{"id", "name"}); got != "ID, NAME" {
		t.Errorf("quoteIdentifiers = %q, 期望 %q", got, "ID, NAME")
	}
}

// 防回归：AUTO_INCREMENT 在 12c+ 目标必须生成 IDENTITY 列。
// 此前版本完全不生成自增（序列从未创建），迁移后表失去自增能力。
func TestGenerateCreateTableDDLIdentity(t *testing.T) {
	a := &Adapter{brand: "Oracle", identityOK: true}
	ddl, err := a.GenerateCreateTableDDL(demoSchema())
	if err != nil {
		t.Fatalf("生成 DDL 失败: %v", err)
	}
	if !strings.Contains(ddl, "ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL") {
		t.Errorf("IDENTITY 列未生成:\n%s", ddl)
	}
	// BY DEFAULT ON NULL：迁移期允许显式插入已有 id 值
	if strings.Contains(ddl, "GENERATED ALWAYS") {
		t.Errorf("不应生成 GENERATED ALWAYS（会拒绝显式插入）:\n%s", ddl)
	}
	// 自增列不得携带列级 DEFAULT（IDENTITY 与 DEFAULT 互斥）
	for _, line := range strings.Split(ddl, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "ID ") && strings.Contains(line, "DEFAULT ") && !strings.Contains(line, "BY DEFAULT ON NULL") {
			t.Errorf("IDENTITY 列不应有 DEFAULT:\n%s", ddl)
		}
	}
}

// 防回归（ORA-01858）：MySQL 风格日期字符串默认值直接嵌入 Oracle DDL，
// Oracle 按 NLS_DATE_FORMAT（'DD-MON-RR'）校验字面量直接建表失败，
// 必须显式 TO_DATE/TO_TIMESTAMP；零值日期丢弃；布尔映射为 1/0。
func TestFormatOracleDefault(t *testing.T) {
	a := &Adapter{brand: "Oracle"}
	cases := []struct {
		baseType string
		in       string
		want     string
	}{
		{"DATE", "2024-01-01", `TO_DATE('2024-01-01', 'SYYYY-MM-DD')`},
		{"DATETIME", "2024-06-01 12:30:45", `TO_TIMESTAMP('2024-06-01 12:30:45', 'SYYYY-MM-DD HH24:MI:SS')`},
		{"DATETIME", "2024-06-01 12:30:45.123456", `TO_TIMESTAMP('2024-06-01 12:30:45.123456', 'SYYYY-MM-DD HH24:MI:SS.FF6')`},
		{"DATETIME", "0000-00-00 00:00:00", ""}, // 零值丢弃
		{"DATE", "0000-00-00", ""},
		{"DATETIME", "CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP"},
		{"TINYINT", "1", "1"},
		{"VARCHAR", "pending", "'pending'"},
		{"BOOLEAN", "true", "1"},
		{"BOOLEAN", "false", "0"},
	}
	for _, c := range cases {
		got := a.formatOracleDefault(types.ColumnMeta{BaseType: c.baseType}, c.in)
		if got != c.want {
			t.Errorf("formatOracleDefault(%s, %q) = %q, 期望 %q", c.baseType, c.in, got, c.want)
		}
	}
}

// 防回归（ORA-01830）：源库日期时间字符串带微秒/时区/缺秒等变体时，
// Oracle TO_TIMESTAMP('YYYY-MM-DD HH24:MI:SS.FF6') 格式严格匹配会报错。
// normalizeTimestampString 必须将所有变体统一为标准格式。
func TestNormalizeTimestampString(t *testing.T) {
	cases := []struct {
		in   string
		isTS bool
		want string
	}{
		// 纯日期 → 补全时间
		{"2024-01-15", false, "2024-01-15 00:00:00"},
		{"2024-01-15", true, "2024-01-15 00:00:00.000000"},
		// 标准日期时间
		{"2024-01-15 10:30:00", false, "2024-01-15 10:30:00"},
		{"2024-01-15 10:30:00", true, "2024-01-15 10:30:00.000000"},
		// 带微秒（不足6位补零）
		{"2024-01-15 10:30:00.1", true, "2024-01-15 10:30:00.100000"},
		{"2024-01-15 10:30:00.123", true, "2024-01-15 10:30:00.123000"},
		{"2024-01-15 10:30:00.123456", true, "2024-01-15 10:30:00.123456"},
		// 带微秒超过6位截断
		{"2024-01-15 10:30:00.1234567", true, "2024-01-15 10:30:00.123456"},
		// DATE 列忽略微秒
		{"2024-01-15 10:30:00.123456", false, "2024-01-15 10:30:00"},
		// T 分隔符
		{"2024-01-15T10:30:00", true, "2024-01-15 10:30:00.000000"},
		// 带时区（去除时区）
		{"2024-01-15T10:30:00+08:00", false, "2024-01-15 10:30:00"},
		{"2024-01-15T10:30:00.123Z", true, "2024-01-15 10:30:00.123000"},
		// 不规则格式（原样返回）
		{"15-JAN-24", false, "15-JAN-24"},
	}
	for _, c := range cases {
		got := normalizeTimestampString(c.in, c.isTS)
		if got != c.want {
			t.Errorf("normalizeTimestampString(%q, isTS=%v) = %q, 期望 %q", c.in, c.isTS, got, c.want)
		}
	}
}

// 防回归：time.Time 值必须被正确格式化，否则 Oracle 驱动会用自己的
// 格式（可能含时区）传给 TO_TIMESTAMP 导致 ORA-01830。
func TestNormalizeTimestampValue(t *testing.T) {
	loc := time.FixedZone("CST", 8*3600)
	ts := time.Date(2024, 1, 15, 10, 30, 0, 123456000, loc)

	// time.Time → TIMESTAMP 列
	got := normalizeTimestampValue(ts, true)
	if got != "2024-01-15 10:30:00.123456" {
		t.Errorf("time.Time → TIMESTAMP = %v, 期望 2024-01-15 10:30:00.123456", got)
	}

	// time.Time → DATE 列
	got = normalizeTimestampValue(ts, false)
	if got != "2024-01-15 10:30:00" {
		t.Errorf("time.Time → DATE = %v, 期望 2024-01-15 10:30:00", got)
	}

	// []byte → 字符串路径
	got = normalizeTimestampValue([]byte("2024-01-15 10:30:00"), true)
	if got != "2024-01-15 10:30:00.000000" {
		t.Errorf("[]byte → TIMESTAMP = %v", got)
	}

	// 非日期类型原样返回
	val := 42
	got = normalizeTimestampValue(val, true)
	if got != 42 {
		t.Errorf("int 原样返回失败: %v", got)
	}
}
