// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSupportedDatabases() {
  return window['go']['main']['App']['GetSupportedDatabases']();
}

export function GetTableSchema(arg1, arg2) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['main']['App']['GetTables'](arg1);
}

export function StartMigration(arg1) {
  return window['go']['main']['App']['StartMigration'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
