// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';

export function GetSupportedDatabases():Promise<Array<string>>;

export function GetTableSchema(arg1:main.TestConnectionRequest,arg2:string):Promise<main.GetTableSchemaResult>;

export function GetTables(arg1:main.TestConnectionRequest):Promise<main.GetTablesResult>;

export function StartMigration(arg1:main.StartMigrationRequest):Promise<types.MigrationReport>;

export function TestConnection(arg1:main.TestConnectionRequest):Promise<main.TestConnectionResult>;
