// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {service} from '../models';
import {history} from '../models';
import {sqllint} from '../models';
import {types} from '../models';

export function CancelMigration():Promise<boolean>;

export function CheckCompatibility(arg1:main.CheckCompatibilityRequest):Promise<service.CompatReport>;

export function ConvertSQL(arg1:service.ConvertSQLRequest):Promise<service.ConvertSQLResult>;

export function DeleteBackup(arg1:main.RestoreRequest):Promise<main.SimpleResult>;

export function DeleteMigrationHistory(arg1:number):Promise<main.SimpleResult>;

export function GenerateConnStrings(arg1:main.ConnectionRequest):Promise<service.ConnStrResult>;

export function GenerateMigrationGuide(arg1:main.ConnectionRequest,arg2:string,arg3:Array<string>):Promise<service.GuideReport>;

export function GetBackupTables(arg1:main.ConnectionRequest):Promise<main.GetBackupTablesResult>;

export function GetMigrationHistory():Promise<Array<history.MigrationRecord>>;

export function GetSupportedDatabases():Promise<Array<string>>;

export function GetTableSchema(arg1:main.ConnectionRequest,arg2:string):Promise<main.GetTableSchemaResult>;

export function GetTables(arg1:main.ConnectionRequest):Promise<main.GetTablesResult>;

export function LintSQL(arg1:main.LintSQLRequest):Promise<sqllint.Report>;

export function OpenInFolder(arg1:string):Promise<main.SimpleResult>;

export function RestoreAllTables(arg1:main.RestoreRequest):Promise<main.RestoreAllResult>;

export function RestoreTable(arg1:main.RestoreRequest):Promise<main.RestoreTableResult>;

export function StartMigration(arg1:main.StartMigrationRequest):Promise<types.MigrationReport>;

export function TestConnection(arg1:main.ConnectionRequest):Promise<main.TestConnectionResult>;

export function ValidateData(arg1:service.ValidateRequest):Promise<service.ValidateReport>;
